apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-express-env
data:
  ME_CONFIG_MONGODB_SERVER: 'mongo'
  ME_CONFIG_MONGODB_PORT: '27017'
  ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
  ME_CONFIG_SITE_BASEURL: '/mongo'
