apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: mongo-express-rs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          ports:
            - containerPort: 8081
          envFrom:
          - configMapRef:
              name: mongo-express-env
